AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates:
    - CodePipeline (Source: GitHub via CodeStar Connection, Build: CodeBuild)
    - CodeBuild project + IAM role
    - S3 website bucket (encrypted with CMK)
    - CloudFront distribution (OAI)
    - KMS CMK (admin: root; used by S3, CloudFront, CodeBuild)
    - Parameters for ACM cert, domain, and GitHub connection/repo

Parameters:
  CertificateArn:
    Type: String
    Description: "ARN of the ACM certificate (must be in us-east-1 for CloudFront)"
  SubDomainName:
    Type: String
    Description: "Domain name for CloudFront (e.g., www.example.com)"
  DomainName:
    Type: String
    Description: "Domain name for CloudFront (e.g., www.example.com)"
  GitHubConnectionArn:
    Type: String
    Description: "ARN of the AWS CodeStar Connection to GitHub"
  GitHubOwner:
    Type: String
    Description: "GitHub user or organization name"
  GitHubRepo:
    Type: String
    Description: "GitHub repository name"
  GitHubBranch:
    Type: String
    Default: main
    Description: "GitHub branch name to use as the pipeline source"
  HostedZoneId:
    Type: String
    Description: "Hosted Zone ID for the domain in Route 53"

Resources:

  ########################################################
  # Roles
  ########################################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-codebuild-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObjectAcl
                Resource:
                  - !Sub "${WebsiteBucket.Arn}/*"
                  - !GetAtt WebsiteBucket.Arn
                  - !Sub "${PipelineArtifactBucket.Arn}/*"
                  - !GetAtt PipelineArtifactBucket.Arn
              # - Effect: Allow
              #   Action:
              #     - kms:Decrypt
              #     - kms:Encrypt
              #     - kms:GenerateDataKey
              #     - kms:DescribeKey
              #   Resource: !Ref WebsiteKmsKey
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action: cloudfront:CreateInvalidation
                Resource: "*"

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-codepipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub "${WebsiteBucket.Arn}/*"
                  - !GetAtt WebsiteBucket.Arn
                  - !Sub "${PipelineArtifactBucket.Arn}/*"
                  - !GetAtt PipelineArtifactBucket.Arn
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - iam:PassRole
                  - codestar-connections:UseConnection
                Resource: 
                  - !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${AWS::StackName}-pipeline
                  - !GetAtt WebsiteCodeBuildProject.Arn
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: !Ref GitHubConnectionArn


  ########################################################
  # KMS CMK
  ########################################################

  WebsiteKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "CMK for encrypting S3 and used by CloudFront and CodeBuild"
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootFullAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"
          - Sid: AllowS3Use
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
          - Sid: AllowCloudFrontUse
            Effect: Allow
            Principal:
              Service:
              - cloudfront.amazonaws.com
              - s3.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:DescribeKey
            Resource: "*"
          - Sid: AllowCodeBuildRoleUse
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-codebuild-role
                - !Sub arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-codepipeline-role
            Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

  ########################################################
  # S3 Website Bucket
  ########################################################
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${DomainName}-website-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref WebsiteKmsKey
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  S3BucketPolicyForCloudFront:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontAccessViaOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: "s3:GetObject"
            Resource: !Sub "${WebsiteBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteDistribution}"

  ########################################################
  # CloudFront Distribution
  ########################################################

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      # HostedZoneName: "usatv.lat."
      HostedZoneId: !Ref HostedZoneId
      Name: "s3-host-landing-page.usatv.lat."
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        Description: !Sub "OAC for ${AWS::StackName}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.DomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases: 
          - !Sub "${SubDomainName}.${DomainName}"
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100



  ########################################################
  # CodeBuild Project
  ########################################################
  WebsiteCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-build"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: WEBSITE_BUCKET
            Value: !Ref WebsiteBucket
          - Name: CLOUDFRONT_DISTRIBUTION_ID
            Value: !Ref WebsiteDistribution
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2

          phases:
            install:
              runtime-versions:
                nodejs: 18
              commands:
                - cd my-landingpage
                - echo "Installing dependencies"
                - if [ -f package.json ]; then npm install; fi
            build:
              commands:
                - echo "Building project"
                - if [ -f package.json ]; then npm run build || true; fi
                - echo "Syncing files to S3"
                - cd build
                - aws s3 sync . s3://$WEBSITE_BUCKET --delete
                - echo "Invalidating CloudFront cache"
                - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
          artifacts:
            files:
              - '**/*'


  ########################################################
  # Artifact Bucket for CodePipeline
  ########################################################
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-pipeline-artifacts"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ########################################################
  # CodePipeline (Source: GitHub via CodeStar connection)
  ########################################################
  WebsitePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${AWS::StackName}-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Sub "${GitHubOwner}/${GitHubRepo}"
                BranchName: !Ref GitHubBranch
                DetectChanges: true
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref WebsiteCodeBuildProject
              RunOrder: 1

Outputs:
  WebsiteBucketName:
    Value: !Ref WebsiteBucket
    Description: "S3 bucket for website hosting"

  CloudFrontDomainName:
    Value: !GetAtt WebsiteDistribution.DomainName
    Description: "CloudFront distribution domain"

  KmsKeyArn:
    Value: !Ref WebsiteKmsKey
    Description: "KMS CMK ARN"

  CodePipelineName:
    Value: !Ref WebsitePipeline
    Description: "CodePipeline name"

  CodeBuildRoleArn:
    Value: !GetAtt CodeBuildRole.Arn
    Description: "ARN of the CodeBuild IAM Role"  

  CodePipelineRoleArn:
    Value: !GetAtt CodePipelineRole.Arn
    Description: "ARN of the CodePipeline IAM Role"